@pyapi_HostAddress = http://localhost:5172

POST {{pyapi_HostAddress}}/dataexporter/retail/parquet?filename=magaza.parquet
Content-Type: text/plain
retail: mssql://testoltp:1433/Retail?driver=ODBC+Driver+17+for+SQL+Server&TrustServerCertificate=true&trusted_connection=true

SELECT * FROM tb_Depo (nolock) where DepoTip=3

###
POST {{pyapi_HostAddress}}/dataexporter/parquet?filename=magaza.parquet
Content-Type: application/json

{
    "ConnectionStrings": {
        "testdb": "mssql://sa:Passw@rd@localhost:1433/TestDb?driver=ODBC+Driver+17+for+SQL+Server&TrustServerCertificate=yes",
        "retail": "mssql://testoltp:1433/Retail?driver=ODBC+Driver+17+for+SQL+Server&TrustServerCertificate=true&trusted_connection=true"
    },
    "DataSources": {
        "retail": {
            "magaza": "SELECT * FROM tb_Depo (nolock) where DepoTip=3"
            }
    },
    "Query": "SELECT * FROM magaza LIMIT 100" 
}

###

GET {{pyapi_HostAddress}}/dict
Accept: application/json    
###

POST {{pyapi_HostAddress}}/run
Content-Type: text/plain

from doviz_kurlari import TCMBKur
from datetime import date

kur_yoneticisi = TCMBKur()
euro_kuru = kur_yoneticisi.kur_getir("USD")
#print(euro_kuru)

gecmis_tarih = date(2024, 5, 15) 
gecmis_kurlar = TCMBKur(tarih=gecmis_tarih)
euro_gecmis = gecmis_kurlar.kur_getir("EUR")
#print(euro_gecmis)

date.today()

# import json

# class Kedi:
#     def __init__(self, ad, tur):
#         self.ad = ad
#         self.tur = tur

# class Köpek:
#     def __init__(self, ad, irk):
#         self.ad = ad
#         self.irk = irk

# def custom_encoder(obj):
#     data = obj.__dict__.copy()
#     data['$type'] = obj.__class__.__name__
#     return data
    
# hayvanlar = [Kedi("Mırnav", "Tekir"), Köpek("Karabaş", "Kangal")]

# json_output = json.dumps(
#     hayvanlar, 
#     default=custom_encoder, 
#     ensure_ascii=False
# )

# print(json_output)

#print("Hello World!")
#import sys
#import pandas as pd
#print(f"Python version: {sys.version}")
#print(f"Pandas version: {pd.__version__}")

